/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2021-09-25 07:11:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.HospitalPic;
import java.util.ArrayList;
import models.Hospital;
import models.Patient;
import models.Doctor;
import java.util.ArrayList;
import models.City;

public final class hospital_005fpics_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/hospital_header_btns.jsp", Long.valueOf(1629017250428L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1631903017580L));
    _jspx_dependants.put("/head.jsp", Long.valueOf(1630685170511L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1632142882333L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.HospitalPic");
    _jspx_imports_classes.add("models.Patient");
    _jspx_imports_classes.add("models.Doctor");
    _jspx_imports_classes.add("models.Hospital");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("models.City");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write(" \t");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"static/images/favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/font-awesome.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/form.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js\" integrity=\"sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.dropdown-toggle::after{\r\n");
      out.write("\t\tcontent:none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js\" integrity=\"sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("     \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/dropzone.min.css\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid  \">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-4 \">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-4  \">\r\n");
      out.write("                    \t<a href=\"index.jsp\" style=\"text-decoration:none\"><img src=\"static/images/logo.jpg\" alt=\"\" class=\"img-fluid\" style=\"height:100px;\"></a>\r\n");
      out.write("                    \t\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-8   pt-3 pb-1\">\r\n");
      out.write("                        <a href=\"index.jsp\" style=\"text-decoration:none\"> <h2 class=\"text-success py-1 font-weight-bold\">Health Care</h2></a>\r\n");
      out.write("                        <p class=\"text-primary text-info\">We take care of your health.</p>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-4  px-5 pt-2  \">\r\n");
      out.write("                <a href=\"hospital.do\" class=\"btn btn-outline-info\">Hospitals</a>\r\n");
      out.write("                <a href=\"doctor.do\" class=\"btn btn-outline-info\">Doctors</a>\r\n");
      out.write("                <button class=\"btn btn-outline-info\">Medicines</button>\r\n");
      out.write("\r\n");
      out.write("                <form action=\"\" class=\"form-inline pt-3 \">\r\n");
      out.write("                    <input type=\"search\" class=\"form-control\" name=\"search\" id=\"id_search\">\r\n");
      out.write("                    <input type=\"submit\" value=\"Search\" name=\"srch_btn\" id=\"id_srch_btn\" class=\"btn btn-info ml-1\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-4  pt-2 \">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col mt-2 text-right\">\r\n");
      out.write("                        \r\n");
      out.write("                        <a href=\"index.jsp\"><i class=\"fa fa-home mr-3 fa-lg \" style=\"cursor: pointer;color:info\"></i></a>\r\n");
      out.write("                        <div class=\"dropdown pr-3\"  style=\"display:inline\">\r\n");
      out.write("                        \t<a href=\"#\" class=\"dropdown-toggle mr-3\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\"><i class=\"fa fa-sliders fa-lg\"></i></a>\r\n");
      out.write("                        \t");
 Hospital hospital = (Hospital)session.getAttribute("hospital");  
      out.write("                      \t \r\n");
      out.write("                        \t");
 Patient patient = (Patient)session.getAttribute("patient");  
      out.write("                      \t \r\n");
      out.write("                        \t");
 Doctor doctor = (Doctor)session.getAttribute("doctor");  
      out.write("                      \t \r\n");
      out.write("                        \t                      \t \r\n");
      out.write("                       \t\r\n");
      out.write("                    \r\n");
      out.write("                        \t<div class=\"dropdown-menu border border-primary ml-n5 pr-0 mt-2\" style=\"min-width:20px;\"  aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("                        \t\t");
 if(hospital==null && patient==null && doctor==null ){ 
      out.write("\r\n");
      out.write("\t                        \t\t<a href=\"login_opt.jsp\" class=\"dropdown-item text-info \"><i class=\"fa fa-sign-in  \"></i> Login</a>\r\n");
      out.write("\t                        \t\t<a href=\"register_opt.jsp\" class=\"dropdown-item text-info \"><i class=\"fa fa-user-plus  \"></i> Register</a>\r\n");
      out.write("\t                     \t   \t");
}else if(hospital!=null){ 
      out.write("\r\n");
      out.write("\t                     \t   \t\t\r\n");
      out.write("\t                     \t   \t\t<a href=\"logout.do\" class=\"dropdown-item text-info\"><i class=\"fa fa-sign-out  \"></i> Logout</a> \r\n");
      out.write("\t                     \t   \t\t<a href=\"hospital_profile.do\" class=\"dropdown-item text-info \"><i class=\"fa fa-user  \"></i> Profile</a> \r\n");
      out.write("\t                     \t   \t");
}else if(doctor!=null){ 
      out.write("\r\n");
      out.write("                     \t   \t\t\r\n");
      out.write("\t                     \t   \t\t<a href=\"logout.do\" class=\"dropdown-item text-info\"><i class=\"fa fa-sign-out  \"></i> Logout</a> \r\n");
      out.write("\t                     \t   \t\t<a href=\"doctor_profile.do\" class=\"dropdown-item text-info \"><i class=\"fa fa-user  \"></i> Profile</a>  \r\n");
      out.write("\t\t                        ");
}else if(patient!=null){ 
      out.write("\r\n");
      out.write("\t\t                        \t<a href=\"logout.do\" class=\"dropdown-item text-info\"><i class=\"fa fa-sign-out  \"></i> Logout</a> \r\n");
      out.write("\t                     \t   \t\t<a href=\"doctor_profile.do\" class=\"dropdown-item text-info \"><i class=\"fa fa-user  \"></i> Profile</a>                  \r\n");
      out.write("\t\t                        ");
 } 
      out.write("  \r\n");
      out.write("                        \t</div>\r\n");
      out.write("                        \t<span class=\"ml-3\"></span>\r\n");
      out.write("                        \t\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                     \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-6 ml-auto\" >\r\n");
      out.write("                        ");
 ArrayList<City> cities = City.getAllCities(); 
      out.write("\r\n");
      out.write("                        <div class=\"form-group pt-4  city-select  \">\r\n");
      out.write("                            <select name=\"\" id=\"\" class=\"form-control\">\r\n");
      out.write("                                <option value='0'>Select city</option>                      \t\t\t                      \t\t\t\r\n");
      out.write("                       \t\t\t");
 int cityId=0;
                       			if(hospital!=null){ cityId= hospital.getCity().getCityId();}
                       			else if(patient!=null){ cityId = patient.getCity().getCityId();}
                       			else if(doctor!=null){ cityId = doctor.getCity().getCityId();}
                       				
                       			
      out.write("\r\n");
      out.write("                       \t\t\t");
 for(City city:cities){ 
      out.write("\r\n");
      out.write("                       \t\t\t\t\r\n");
      out.write("                       \t\t\t\t");
if(cityId!=0 && city.getCityId()==cityId){ 
      out.write("\r\n");
      out.write("                       \t\t\t\t<option value=\"");
      out.print(city.getCityId() );
      out.write("\" selected> ");
      out.print( city.getCity()+" ("+city.getState().getState()+")"  );
      out.write(" </option>\t\r\n");
      out.write("                       \t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("                       \t\t\t\t<option value=\"");
      out.print(city.getCityId() );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( city.getCity()+" ("+city.getState().getState()+")"  );
      out.write(" </option>\r\n");
      out.write("                       \t\t\t\t");
 }
      out.write("\r\n");
      out.write("                       \t\t\t");
} 
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <span class=\"text-primary text-center ml-3\">Welcome ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospital.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patient.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${doctor.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </span>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("    <div class=\"navigate border border-info mb-3\" style=\"background-color:#131324\">\r\n");
      out.write("        <div class=\"container \">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col py-2\">\r\n");
      out.write("               \t<a href=\"index.jsp\">Home </a> <span class=\"text-white\">></span>\r\n");
      out.write("                <a href=\"\">Profile Pics </a> <span class=\"text-white\">></span>\r\n");
      out.write("                \r\n");
      out.write("                    \r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("<div class=\"container  \">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-2\"></div>\r\n");
      out.write("        <div class=\"col-10 text-right\">\r\n");
      out.write("           <a href=\"hospital_dashboard.do\" class=\"btn btn-success\">Dashboard</a>\r\n");
      out.write("           <a href=\"hospital_profile.do\" class=\"btn btn-success\">Profile</a>\r\n");
      out.write("           <a href=\"hospital_pics.do\" class=\"btn btn-success\">ProfilePics</a> \r\n");
      out.write("           <a href=\"hospital_facilities.do\" class=\"btn btn-success\">Facilities</a> \r\n");
      out.write("           <a href=\"new_admission.do\" class=\"btn btn-success\">New Admission</a> \r\n");
      out.write("           <a href=\"patient_profiles.do\" class=\"btn btn-success\">Patients</a> \r\n");
      out.write("           <a href=\"applications.do\" class=\"btn btn-success\">Applications</a> \r\n");
      out.write("           <!-- <a href=\"assign_room_bed.do\" class=\"btn btn-success\">Assign Room and Bed</a>  -->\r\n");
      out.write("           <!-- <a href=\"patient_profiles.do\" class=\"btn btn-success\">Patient Profiles</a> \r\n");
      out.write("           <a href=\"patient_test_reports.do\" class=\"btn btn-success\">Patient Test Reports</a> --> \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("    <div class=\"main_body\">\r\n");
      out.write("        <h3 class=\"text-info text-center pt-3\">Profile Pics -</h3>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container border-top border-info \" style=\"min-height: 500px;\">\r\n");
      out.write("            <div class=\"row pt-4 \">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    \r\n");
      out.write("                    <ul class=\"nav nav-pills\" id=\"myTab\"  >\r\n");
      out.write("\t\t\t\t\t  <li class=\"nav-item\"  >\r\n");
      out.write("\t\t\t\t\t    <a class=\"nav-link active \" id=\"id_allPics\" data-toggle=\"tab\" href=\"#home\"  >All Uploaded Pics</a>\r\n");
      out.write("\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t  <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("\t\t\t\t\t    <a class=\"nav-link\" id=\"id_uploadPics\" data-toggle=\"tab\" href=\"#profile\"  >Uplaod New Pics</a>\r\n");
      out.write("\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-content p-5\" id=\"myTabContent\">\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  <div class=\"tab-pane fade show active\" id=\"home\" role=\"tabpanel\" aria-labelledby=\"home-tab\">\r\n");
      out.write("\t\t\t\t\t  \t \r\n");
      out.write("\t\t\t\t\t  \t   <ul class=\"nav nav-pills\" id=\"all-tabs1\">\r\n");
      out.write("\t                       <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_interior1\" class=\"nav-link active\" data-toggle=\"tab\">Interior</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                       <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_exterior1\" class=\"nav-link\" data-toggle=\"tab\">Exterior</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                       <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_parking1\" class=\"nav-link\" data-toggle=\"tab\">Parking</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                       <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_rooms1\" class=\"nav-link\" data-toggle=\"tab\">Rooms</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                        <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_ot1\" class=\"nav-link\" data-toggle=\"tab\">Operation-Theatre</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                        <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_reception1\" class=\"nav-link\" data-toggle=\"tab\">Reception</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                   </ul>\r\n");
      out.write("\t\t\t\t\t\t   ");
 ArrayList<HospitalPic> hospitalPics = (ArrayList<HospitalPic>)request.getAttribute("hospitalPics"); 
						   
						   
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t    \r\n");
      out.write("\t\t                   <div class=\"tab-content\" id=\"all-panes1\">\r\n");
      out.write("\t\t                        <div class=\"tab-pane show active fade p-3 card-columns\" id=\"id_interior1\">\r\n");
      out.write("\t\t                         ");
int flag = 0;
		                           for(HospitalPic hospitalPic: hospitalPics){  
      out.write("\r\n");
      out.write("\t\t                            \t \r\n");
      out.write("\t                            \t");
 if(hospitalPic.getPicType().getPicTypeId()==1){
	                            	 	flag++; 
      out.write("\r\n");
      out.write("\t                            \t \t<div class=\"card\">\r\n");
      out.write("\t                            \t \t <img src=\"showHospitalPics.do?pic_path=");
      out.print( hospitalPic.getPicPath() );
      out.write("\"   width=\"320px\">\r\n");
      out.write("\t                                 \t</div>\t\r\n");
      out.write("\t\t                              ");
}}
		                          if(flag==0){  
      out.write("\r\n");
      out.write("\t                            \t <h3> No image</h3>\r\n");
      out.write("\t                             ");
 } 
      out.write("\t\t                      \r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        \r\n");
      out.write("\t\t                        <div class=\"tab-pane fade p-3 card-columns\" id=\"id_exterior1\">\r\n");
      out.write("\t\t                            ");
 int flag1 = 0;
		                           for(HospitalPic hospitalPic: hospitalPics){  
      out.write("\r\n");
      out.write("\t\t                            \t \r\n");
      out.write("\t                            \t");
 if(hospitalPic.getPicType().getPicTypeId()==2){
	                            	 	flag1++; 
      out.write("\r\n");
      out.write("\t                            \t \t<div class=\"card\">\r\n");
      out.write("\t                            \t \t <img src=\"showHospitalPics.do?pic_path=");
      out.print( hospitalPic.getPicPath() );
      out.write("\"   width=\"320\" >\r\n");
      out.write("\t                                 \t</div>\r\n");
      out.write("\t\t                              ");
}}
		                          if(flag1==0){  
      out.write("\r\n");
      out.write("\t                            \t <h3> No image</h3>\r\n");
      out.write("\t                             ");
 } 
      out.write("\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        <div class=\"tab-pane fade p-3 card-columns\" id=\"id_parking1\">\r\n");
      out.write("\t\t                             ");
 int flag3 = 0;
		                           for(HospitalPic hospitalPic: hospitalPics){  
      out.write("\r\n");
      out.write("\t\t                            \t \r\n");
      out.write("\t                            \t");
 if(hospitalPic.getPicType().getPicTypeId()==3){
	                            	 	 flag3++; 
      out.write("\r\n");
      out.write("\t                            \t \t <div class=\"card\">\r\n");
      out.write("\t                            \t \t \t<img src=\"showHospitalPics.do?pic_path=");
      out.print( hospitalPic.getPicPath() );
      out.write("\"   width=\"320\" >\r\n");
      out.write("\t                            \t \t </div>\r\n");
      out.write("\t                            \t \t \r\n");
      out.write("\t                                 \r\n");
      out.write("\t\t                              ");
}}
		                          if(flag3==0){  
      out.write("\r\n");
      out.write("\t                            \t <h3> No image</h3>\r\n");
      out.write("\t                             ");
 } 
      out.write("\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        <div class=\"tab-pane fade p-3 card-columns\" id=\"id_rooms1\">\r\n");
      out.write("\t\t                             ");
 int flag4 = 0;
		                           for(HospitalPic hospitalPic: hospitalPics){  
      out.write("\r\n");
      out.write("\t\t                            \t \r\n");
      out.write("\t                            \t");
 if(hospitalPic.getPicType().getPicTypeId()==4){
	                            	 	flag4++; 
      out.write("\r\n");
      out.write("\t                            \t \t <div class=\"card\">\r\n");
      out.write("\t                            \t \t \t<img src=\"showHospitalPics.do?pic_path=");
      out.print( hospitalPic.getPicPath() );
      out.write("\"  width=\"320\" >\r\n");
      out.write("\t                            \t \t </div>\r\n");
      out.write("\t\t                              ");
}}
		                          if(flag4==0){  
      out.write("\r\n");
      out.write("\t                            \t <h3> No image</h3>\r\n");
      out.write("\t                             ");
 } 
      out.write("\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        <div class=\"tab-pane fade p-3 card-columns\" id=\"id_ot1\">\r\n");
      out.write("\t\t                            ");
 int flag5 = 0;
		                           for(HospitalPic hospitalPic: hospitalPics){  
      out.write("\r\n");
      out.write("\t\t                            \t \r\n");
      out.write("\t                            \t");
 if(hospitalPic.getPicType().getPicTypeId()==5){
	                            	 	flag5++; 
      out.write("\r\n");
      out.write("\t                            \t \t <div class=\"card\">\r\n");
      out.write("\t                            \t \t \t<img src=\"showHospitalPics.do?pic_path=");
      out.print( hospitalPic.getPicPath() );
      out.write("\"   width=\"320\"  >\r\n");
      out.write("\t                            \t \t </div>\r\n");
      out.write("\t\t                              ");
}}
		                          if(flag5==0){  
      out.write("\r\n");
      out.write("\t                            \t <h3> No image</h3>\r\n");
      out.write("\t                             ");
 } 
      out.write("\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        <div class=\"tab-pane fade p-3 card-columns\" id=\"id_reception1\">\r\n");
      out.write("\t\t                         \t");
 int flag6 = 0;
		                           for(HospitalPic hospitalPic: hospitalPics){  
      out.write("\r\n");
      out.write("\t\t                            \t \r\n");
      out.write("\t                            \t");
 if(hospitalPic.getPicType().getPicTypeId()==6){
	                            	 	flag6++; 
      out.write("\r\n");
      out.write("\t                            \t \t <div class=\"card\">\r\n");
      out.write("\t                            \t \t \t<img src=\"showHospitalPics.do?pic_path=");
      out.print( hospitalPic.getPicPath() );
      out.write("\"  width=\"320\"  >\r\n");
      out.write("\t                            \t \t </div>\r\n");
      out.write("\t\t                              ");
}}
		                          if(flag6==0){  
      out.write("\r\n");
      out.write("\t                            \t <h3> No image</h3>\r\n");
      out.write("\t                             ");
 } 
      out.write("\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("               \r\n");
      out.write("\t\t\t\t\t  \t \r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  <div class=\"tab-pane fade\" id=\"profile\" role=\"tabpanel\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("\t\t\t\t\t    <ul class=\"nav nav-tabs \" id=\"all-tabs\">\r\n");
      out.write("\t                       <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_interior\" class=\"nav-link active\" data-toggle=\"tab\">Interior</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                       <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_exterior\" class=\"nav-link\" data-toggle=\"tab\">Exterior</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                       <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_parking\" class=\"nav-link\" data-toggle=\"tab\">Parking</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                       <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_rooms\" class=\"nav-link\" data-toggle=\"tab\">Rooms</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                        <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_ot\" class=\"nav-link\" data-toggle=\"tab\">Operation-Theatre</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                        <li class=\"nav-item\">\r\n");
      out.write("\t                           <a href=\"#id_reception\" class=\"nav-link\" data-toggle=\"tab\">Reception</a>\r\n");
      out.write("\t                       </li>\r\n");
      out.write("\t                   </ul>\r\n");
      out.write("\r\n");
      out.write("\t                    <div class=\"tab-content\" id=\"all-panes\">\r\n");
      out.write("\t                        <div class=\"tab-pane show active fade\" id=\"id_interior\">\r\n");
      out.write("\t                            <form class=\"dropzone pt-4 mt-5 mx-4 border border-primary\" id=\"picup_interior\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"mt-4 btn btn-primary ml-4\" type=\"button\" id=\"btn_interior\" value=\"Upload\"> \r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <div class=\"tab-pane fade\" id=\"id_exterior\">\r\n");
      out.write("\t                            <form class=\"dropzone pt-4 mt-5 mx-4 border border-primary\" id=\"picup_exterior\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"mt-4 btn btn-primary ml-4\" type=\"button\" id=\"btn_exterior\" value=\"Upload\"> \r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <div class=\"tab-pane fade\" id=\"id_parking\">\r\n");
      out.write("\t                            <form class=\"dropzone pt-4 mt-5 mx-4 border border-primary\" id=\"picup_parking\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"mt-4 btn btn-primary ml-4\" type=\"button\" id=\"btn_parking\" value=\"Upload\"> \r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <div class=\"tab-pane fade\" id=\"id_rooms\">\r\n");
      out.write("\t                            <form class=\"dropzone pt-4 mt-5 mx-4 border border-primary\" id=\"picup_rooms\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"mt-4 btn btn-primary ml-4\" type=\"button\" id=\"btn_rooms\" value=\"Upload\"> \r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <div class=\"tab-pane fade\" id=\"id_ot\">\r\n");
      out.write("\t                            <form class=\"dropzone pt-4 mt-5 mx-4 border border-primary\" id=\"picup_ot\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"mt-4 btn btn-primary ml-4\" type=\"button\" id=\"btn_ot\" value=\"Upload\"> \r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <div class=\"tab-pane fade\" id=\"id_reception\">\r\n");
      out.write("\t                            <form class=\"dropzone pt-4 mt-5 mx-4 border border-primary\" id=\"picup_reception\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"mt-4 btn btn-primary ml-4\" type=\"button\" id=\"btn_reception\" value=\"Upload\"> \r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("               \r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<div class=\"footer text-center pt-5 \">\r\n");
      out.write("    <p >Copyright © 2000-2021 HealthCare.com. All rights reserved</p>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("    <script src=\"static/js/dropzone.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("\t\t\r\n");
      out.write("    \r\n");
      out.write("    \tlet forms = document.querySelectorAll('.dropzone');\r\n");
      out.write("    \tforms.forEach((form,index)=>{\r\n");
      out.write("    \t\t  let form_id = form.id; //\r\n");
      out.write("    \t\t  Dropzone.autoDiscover = false;\r\n");
      out.write("    \t\t  //console.log(Dropzone.options);\r\n");
      out.write("    \t\t  Dropzone.options.form_id=\r\n");
      out.write("    \t\t\t{\r\n");
      out.write("    \t\t\t\tparamName: 'file',\r\n");
      out.write("    \t\t\t\tmaxFilesize: 5,\r\n");
      out.write("    \t\t\t\tuploadMultiple: true,\r\n");
      out.write("    \t\t\t\tcreateImageThumbnails: true,\r\n");
      out.write("    \t\t\t\tmaxFiles: 1,\r\n");
      out.write("    \t\t\t\tacceptedFiles: '.jpeg,.png,.gif,.jfif,.jpg',\r\n");
      out.write("    \t\t\t\taddRemoveLinks: true,\r\n");
      out.write("    \t\t\t\tautoProcessQueue: false\r\n");
      out.write("    \t\t\t};\r\n");
      out.write("    \t\t   \r\n");
      out.write("    \t\t  console.log(index, '!!!!!!!!!!!!!!!!!!!');\r\n");
      out.write("    \t\t  let id = index+1;            // why 10 print ho rha tha \r\n");
      out.write("    \t\t  let dropzone = new Dropzone('#'+form.id, {url:'hospital_pics_upload.do?pic_type_id='+id});\r\n");
      out.write("    \t\t  \r\n");
      out.write("    \t\t  let btn = document.querySelector('#btn'+form.id.substring(5)); \r\n");
      out.write("    \t\t   \r\n");
      out.write("    \t\t  btn.dz = dropzone;\r\n");
      out.write("    \t\t  btn.addEventListener('click',()=>{\r\n");
      out.write("    \t\t  \tbtn.dz.processQueue();\r\n");
      out.write("    \t\t  \r\n");
      out.write("    \t\t  });\r\n");
      out.write("    \t});\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t</script>\r\n");
      out.write("     \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
